version: 0.2

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the image
      - echo "No install commands"
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"