version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - echo "No pre-build commands"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run test
artifacts:
  files:
    - "**/*"