version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "No pre-build commands"
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"